### PR TITLE
make undo-skipping optional for auto-close insertion/deletion

### LINKED ISSUE #172: Auto-generated closing tags do not disappear on undo
To reproduce:
1. Start editing a .jsx file
2. Type an opening html tag (e.g. `<div>`). The closing `</div>` tag will be automatically generated.
3. Press undo. The `<div>` tag will be removed, but the closing `</div>` tag will remain

### PR DESCRIPTION
**Pull request by t9md**
FIx #172.

This PR add config option.

- `skipUndoStackForAutoCloseInsertion`: default `true` to not break previous behavior.

When set to `false`, auto-close-tag insertion/deletion no longer **skip** undo stack of buffer change history.

## Background:

- I'm maintainer of vim-mode-plus package
- One of my user report `undo` do not correctly undo the all insertion.
- I investigated and found the cause is `undo: 'skip'` option.
- I understand the purpose, why you explicitly set this option.
- But vim's undo handling is a bit different, vim bundle all the changes made in `insert-mode` and undo all changes by single `undo`.
  - `atom-ract`'s default `undo: 'skip'` behavior is not well fit of this behavior.
  - So hope you consider to allow this undo-skipping optional.

https://github.com/t9md/atom-vim-mode-plus/issues/778#issuecomment-299860100

Thanks

### CODE REVIEW

File: lib/atom-react.coffee [hunk 1]
```diff
@@ -244,7 +248,12 @@ class AtomReact
         line = lines[row]
 
       if tagName?
-        editor.insertText('</' + tagName + '>', {undo: 'skip'})
+        if atom.config.get('react.skipUndoStackForAutoCloseInsertion')
+          options = {undo: 'skip'}
+        else
+          options = {}
+        console.log options
```
Comment (orktes) [inline lib/atom-react.coffee]: Can you remove this console.log? :)

**Comment by orktes** [comment]
Thanks for the PR!

**Comment by t9md** [comment]
Thank you!

File: lib/atom-react.coffee (hunk 1 above)
Comment (t9md) [inline lib/atom-react.coffee]: Oh sorry for that.
